version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongoflix-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mongoflix
    volumes:
      - mongodb_data:/data/db
      - ./data:/data/import
    networks:
      - mongoflix-network

  # Service de génération de données (Python)
  seeder:
    image: python:3.11-slim
    container_name: mongoflix-seeder
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - mongoflix-network
    depends_on:
      - mongodb
    # On installe les dépendances et on lance le script
    command: >
      sh -c "pip install pymongo faker && python seed.py"
    restart: "no"

  mongo-init:
    image: mongo:7.0
    container_name: mongoflix-init
    depends_on:
      - mongodb
    volumes:
      - ./data:/data/import
    networks:
      - mongoflix-network
    entrypoint: >
      bash -c "
      echo 'Waiting for MongoDB to be ready...'
      sleep 10
      echo 'Importing initial BSON data...'
      mongorestore --host mongodb --db mongoflix /data/import/
      echo 'Import completed!'
      "
    restart: "no"

  backend:
    build: ./backend
    container_name: mongoflix-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/mongoflix
      - PORT=3000
      - NODE_ENV=development
    depends_on:
      mongodb:
        condition: service_started
      mongo-init:
        condition: service_completed_successfully
      seeder:
        condition: service_completed_successfully
    networks:
      - mongoflix-network
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

  frontend:
    build: ./frontend
    container_name: mongoflix-frontend
    restart: unless-stopped
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - mongoflix-network
    volumes:
      - ./frontend:/usr/share/nginx/html:ro

volumes:
  mongodb_data:

networks:
  mongoflix-network:
    driver: bridge